### PR TITLE
for issues #48 and #49

### PR DESCRIPTION
**Pull request by Sunying-RONG**
fixed sidebar and swiper slide added, two main parts "Freelancer" and "Client"
#48 
#49 
#27

### CODE REVIEW

**Comment by Sunying-RONG** [comment]
I use Bootstrap in the commit "0db9fd6", the code is more clear than previous.

**Comment by echolabstech** [comment]
@Sunying-RONG I can't actually see the changes. Can you screenshot for me.

**Comment by echolabstech** [comment]
@Sunying-RONG getting feedback from marketing before we merge

**Comment by echolabstech** [comment]
@Sunying-RONG  lets add a signup button between slideshow and clients
image

**Comment by echolabstech** [comment]
@Sunying-RONG need a signup button here
image

**Comment by echolabstech** [comment]
@Sunying-RONG replace stock images with images from here: http://old.coderbunker.com/events
image

**Comment by echolabstech** [comment]
Trust elements
image

 should look more like this
image

**Comment by echolabstech** [comment]
@Sunying-RONG add a "learn more" link under the slideshow next to the signup button
image

**Comment by echolabstech** [comment]
@Sunying-RONG add a "learn more" link next to the signup button
image

**Comment by echolabstech** [comment]
@Sunying-RONG so I'm lookin at the `_site` folder. Why is this here?

**Comment by Sunying-RONG** [comment]
> 
> 
> @Sunying-RONG so I'm lookin at the `_site` folder. Why is this here?

I added _site to .gitignore file now, I think it's because "jekyll serve", it creates _site automatically.

**Pull request closed without merging**
